### PR TITLE
V1

### PR DESCRIPTION
**Pull request by Adelenade**

### CODE REVIEW

**Comment by Adelenade** [comment]
Just a quick message to announce that the v1 release will match the release of macOS Ventura !

Normally, I should focus on bug tracking and release the actual set of capabilities in a stable release !

**Comment by Adelenade** [comment]
Actually, the app is too laggy to be released. Don't know why, but it uses a lot of ram. I think it's due to the custom sliders but i can't realy figure out why it's lagging.
So no new features or anything else will be added until the app is optimised.

**Comment by PnsDev** [comment]
Have there been any improvements to the lag issue? Or is this project dead for the time being?

> Actually, the app is too laggy to be released. Don't know why, but it uses a lot of ram. I think it's due to the custom sliders but i can't realy figure out why it's lagging. So no new features or anything else will be added until the app is optimised.

**Comment by Adelenade** [comment]
> Have there been any improvements to the lag issue? Or is this project dead for the time being?

For now the app développement is paused as a rewrite is needed and even if it's already started it needs a lot of work and as im really busy nowadays I can't really work on it actively. 
More than just performance issues, the app itself does nothing but providing a native ui to the goxlr utility, and as I didn't' managed to get a core audio driver working to properly handle the audio part of the goxlr Im not as motivated as before, the advantages of the app compared to having only the utility aren't really obvious anymore, so yeah for now I don't work on the project, but if someone wanna help me finishing the project I'm ready to spend time on it again ofc !

**Comment by Adelenade** [comment]
Merging as main version of the app is even worse than this. This will allow us to move to another clean branch and restart the development using the new GoXlrKit.

**Pull request merged**
